market_flask/app/models.py
from . import db


class Image(db.Model):
    __tablename__ = 'images'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    file = db.Column(db.String)
    products = db.relationship('Product', backref='image', lazy='dynamic')

    def __repr__(self):
        return f'{self.file}'


class Year(db.Model):
    __tablename__ = 'years'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    year = db.Column(db.String)
    products = db.relationship('Product', backref='year', lazy='dynamic')

    def __repr__(self):
        return f'{self.year}'


class Brand(db.Model):
    __tablename__ = 'brands'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    brand = db.Column(db.String)
    products = db.relationship('Product', backref='brand', lazy='dynamic')

    def __repr__(self):
        return f'{self.brand}'


class Screen(db.Model):
    __tablename__ = 'screens'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    screen = db.Column(db.String)
    specifications = db.relationship('Specification', backref='screen', lazy='dynamic')

    def __repr__(self):
        return f'{self.screen}'


class Processor(db.Model):
    __tablename__ = 'processors'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    processor = db.Column(db.String)
    specifications = db.relationship('Specification', backref='processor', lazy='dynamic')

    def __repr__(self):
        return f'{self.processor}'


class Memory(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    memory = db.Column(db.String)
    specifications = db.relationship('Specification', backref='memory', lazy='dynamic')

    def __repr__(self):
        return f'{self.memory}'


class Storage(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    storage = db.Column(db.String)
    specifications = db.relationship('Specification', backref='storage', lazy='dynamic')

    def __repr__(self):
        return f'{self.storage}'


class Specification(db.Model):
    __tablename__ = 'specifications'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    processor_id = db.Column(db.Integer, db.ForeignKey(Processor.id))
    screen_id = db.Column(db.Integer, db.ForeignKey(Screen.id))
    memory_id = db.Column(db.Integer, db.ForeignKey(Memory.id))
    storage_id = db.Column(db.Integer, db.ForeignKey(Storage.id))
    products = db.relationship('Product', backref='spec', lazy='dynamic')
    

    def __repr__(self):
        return f'{self.screen}, {self.processor}, {self.memory}, {self.storage}'


class Product(db.Model):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    price = db.Column(db.String)
    year_id = db.Column(db.Integer, db.ForeignKey(Year.id))
    spec_id = db.Column(db.Integer, db.ForeignKey(Specification.id))
    brand_id = db.Column(db.Integer, db.ForeignKey(Brand.id))
    image_id = db.Column(db.Integer, db.ForeignKey(Image.id))

market_flask/app/__init__.py
import os
from flask_sqlalchemy import SQLAlchemy
from flask import Flask
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView

db = SQLAlchemy()
admin = Admin()

def create_app(config_name):
	
	app = Flask(__name__)

	# import configuration
	cfg = os.path.join(os.getcwd(), 'config', config_name + '.py')
	app.config.from_pyfile(cfg)

	# initialize extensions
	db.init_app(app)
	admin.init_app(app)

	with app.app_context():
		from .models import Product, Year, Brand, Specification ,Screen, Processor, Memory, Storage, Image
		admin.add_view(ModelView(Product, db.session()))
		admin.add_view(ModelView(Year, db.session()))
		admin.add_view(ModelView(Brand, db.session()))
		admin.add_view(ModelView(Specification, db.session()))
		admin.add_view(ModelView(Screen, db.session()))
		admin.add_view(ModelView(Processor, db.session()))
		admin.add_view(ModelView(Memory, db.session()))
		admin.add_view(ModelView(Storage, db.session()))
		admin.add_view(ModelView(Image, db.session()))

	# import blueprints
	from .notebooks import notebooks as notebooks_blueprint
	app.register_blueprint(notebooks_blueprint, url_prefix='/notebooks')

	return app

market_flask/app/notebooks/__init__.py
from flask import Blueprint

notebooks = Blueprint('notebooks', __name__)

from . import routes

market_flask/app/notebooks/routes.py
from flask import render_template
from ..models import Product
from . import notebooks
from .. import db


@notebooks.route('/')
def index():
    products = Product.query.all()
    return render_template('notebooks.html', products=products, quantity=len(products))


@notebooks.route('/<int:id>')
def personal(id):
    product = Product.query.get(id)
    return render_template('product.html', product=product)

market_flask/app/templates/layout.html
<!DOCTYPE html>

<html>
	
  <head>
    <meta charset="utf-8"/>
    <meta content="initial-scale=1, width=device-width" name="viewport"/>
  	<title>{% block title %}{% endblock %}</title>
    {% block links %}{% endblock %}
	</head>

	<body>

      <header id="showcase" class="grid">
        <div class="bg-image"></div>
        <div class="content-wrap">
          <h1>Nor<span class="orange">d</span>ream Market</h1>
          <p>MODERN PYTHON SOLUTIONS</p>
        </div>
      </header>
      
      {% block main %}{% endblock %}
  
      <footer id="footer" class="grid">
        <div class="footer-wrap">
          <p>© Copyright 2018 Nordream</p>
          <p>All Rights Reserved</p>
        </div>
      </footer>
      
  </body>

</html>

market_flask/app/templates/notebooks.html
{% extends "layout.html" %}

{% block title %} Notebooks {% endblock %}


{% block links %}

<link href="{{ url_for('static', filename='styles_index.css') }}" rel="stylesheet"/>

{% endblock %}


{% block main %}

<main id="main">

	<section id="theme" class="grid">
		<div class="theme-wrap">
			<h2>Notebooks | <span class="fading-grey">{{ quantity }} models</span></h2>
		</div>
	</section>
	
	<section id="gallery" class="grid">
	{% for product in products %}
		<div class="image-wrap">
			<a href="{{ url_for('notebooks.personal', id=product.id) }}"><img src="{{ url_for('static', filename='images/' + product.image.file) }}"></a>
		<p> {{ product.brand }} {{ product.spec.screen}}-{{ product.spec.processor}}-{{ product.spec.memory}}-{{ product.spec.storage}}</p>
		<h3> {{ product.price }} </h3>
		</div>
	{% endfor %}
	</section>

</main>

{% endblock %}

market_flask/app/templates/product.html
{% extends "layout.html" %}

{% block title %} Cherry notebook {% endblock %}


{% block links %}

<link href="{{ url_for('static', filename='styles_product.css') }}" rel="stylesheet"/>

{% endblock %}


{% block main %}

		<main id="main">
			<section id="theme" class="grid">
				<div class="theme-wrap">
					<h2> {{ product.brand}} notebook | <span class="fading-grey">Model: {{ product.spec.screen}}-{{ product.spec.processor}}-{{ product.spec.memory}}-{{ product.spec.storage}}</span></h2>
				</div>
			</section>
	

			<section id="info" class="grid">
				<div class="image-wrap">
					<img src="{{ url_for('static', filename='images/' + product.image.file) }}">
				</div>
				<div class="specification-wrap">
					<h2>Specification</h2>
					<ul>
						<li>Screen size: {{ product.spec.screen }}</li>
						<li>Processor: {{ product.spec.processor }}</li>
						<li>Memory size: {{ product.spec.memory }}</li>
						<li>Hard drive size: {{ product.spec.storage }}</li>
						<li>Year: {{ product.year }}</li>
					</ul>
				</div>
				<div class="price-wrap">
					<h2> {{ product.price }}</h2>
					<a href="" class="btn">Buy me</a>
				</div>

				<div class="description-wrap">
					
				</div>
			</section>

		</main>

{% endblock %}